name: Github Actions 배포 테스트

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install pnpm
        run: npm install -g pnpm

      - name: 라이브러리 설치
        run: pnpm install

      - name: 테스트 실행하기
        run: pnpm test

      - name: 빌드
        run: pnpm build
